### ISSUE TITLE
No such file or directory, open '/c/source/evernote-to-obsidian/template.tmpl'

### ISSUE THREAD

**Issue by AlexV-L** [dmuth/evernote-to-obsidian#9]
When running `./convert-evernote-to-markdown.sh ./evernote-notebooks/Ideas.enex` I am getting the following error:

```
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/c/source/evernote-to-obsidian/template.tmpl'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at setOptions (C:\ProgramData\nvm\v18.16.0\node_modules\yarle-evernote-to-md\dist\yarle.js:78:71)
    at Object.dropTheRope (C:\ProgramData\nvm\v18.16.0\node_modules\yarle-evernote-to-md\dist\yarle.js:164:5)
    at Object.run (C:\ProgramData\nvm\v18.16.0\node_modules\yarle-evernote-to-md\dist\dropTheRopeRunner.js:57:47)
    at Object.<anonymous> (C:\ProgramData\nvm\v18.16.0\node_modules\yarle-evernote-to-md\dist\dropTheRope.js:30:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '/c/source/evernote-to-obsidian/template.tmpl'
}
```

I am using Git Bash and Node.js v18.16.0 on a Windows 10 Dell Laptop. Everything in my project structure looks to be in alignment with the readme. Any ideas? 

![image](https://user-images.githubusercontent.com/104666084/233820762-01d41047-b338-4310-afc5-c2a5a30f6606.png)

**Comment by dmuth** [comment]
Hi, I'm afraid not, because I don't do any windows development (Mac and Linux user here).

Assuming you haven't already done so, you could try `ls -l /c/source/(REST OF THE PATH)` and `cat /c/source/(REST OF THE PATH)` to make sure that paths and permissions are correct.

I'll gladly keep this ticket open indefinitely, in case anyone else runs into a similar problem and has a solution.

**Comment by AlexV-L** [comment]
Ah thank you for that information. It appears that the error was because I was using a Unix-style path (`/c/source/evernote-to-obsidian/evernote-notebooks`) while the actual path is in Windows-style (`C:\source\evernote-to-obsidian\evernote-notebooks`). After replacing the `%DIR%` variable in the `config.json.in` with a hardcoded windows path `C:/source/evernote-to-obsidian` it worked perfectly.

**Comment by dmuth** [comment]
Oh that's fantastic!  I'm surprised windows-style paths worked in `bash`, but I ain't complaining!  I'll close this one out. :-)
